### ISSUE TITLE
Eanble the association of channels with servers/brokers

### ISSUE THREAD

**Issue by bruno-baloi-mulesoft** [asyncapi/asyncapi#475] opened 2021-01-08 16:20 UTC
There is a significant need for the ability to design Async APIs that perform multiple activities.

For instance consuming events over one type of transport/server (i.e. MQTT) and subsequently generating events over other types of transports (i.e. AMQP). Typically if an Async API implements some type of event choreography that occurs quite often. Additionally there can be APIs that act as Transport bridges and applying certain types event filtering or processing.

In these types of scenarios the Async API spec will need to define the servers, and the channels need to have a mechanism whereby they can indicate what server they are bound to.

**Comment by fmvilas** [comment] 2021-01-08 17:07
Duplicate of #255?

**Comment by bruno-baloi-mulesoft** [comment] 2021-01-08 17:51
Thx Fran. So can we expect the update to the spec then ?

**Comment by fmvilas** [comment] 2021-01-31 19:40
I'm working on the roadmap for 2.1.0. Don't have a date yet but will update here as soon as we know. Thanks for your patience.

**Closed by fmvilas** 2021-01-31 19:40 UTC
Labels: feature request
